### PR TITLE
Adding JSC client Support to new RDS ani Describe Db Types Api

### PR DESCRIPTION
**Pull request by adarshkoyya**

### CODE REVIEW

**Comment by anantkaushik89** [comment]
Can someone from RDS team confirm that all changes/review comments are done?

**Comment by adarshkoyya** [comment]
@shashankchakelam  Could you please confirm.

**Comment by adarshkoyya** [comment]
@shashankchakelam  Could you please apporve

**Comment by shashankchakelam** [comment]
@anantkaushik89 , @adarshkoyya : changes look good

**Pull request merged**
